// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFFsFXj-rCzp7bbtAFXPKWcJ686twGkg0',
    appId: '1:695875489529:web:4b0883826eadc4e2bf1c28',
    messagingSenderId: '695875489529',
    projectId: 'baby-log-894ac',
    authDomain: 'baby-log-894ac.firebaseapp.com',
    storageBucket: 'baby-log-894ac.firebasestorage.app',
    measurementId: 'G-0CJ0CPRZ1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRvHno_qplxRqxokdyKWc_J-B_aXYkVQw',
    appId: '1:695875489529:android:3ec2c2cf0e7dbafabf1c28',
    messagingSenderId: '695875489529',
    projectId: 'baby-log-894ac',
    storageBucket: 'baby-log-894ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsz8cQzLARt2pBPVLm2g3vXed0v7E8aIE',
    appId: '1:695875489529:ios:9146ccdc73aa5cfcbf1c28',
    messagingSenderId: '695875489529',
    projectId: 'baby-log-894ac',
    storageBucket: 'baby-log-894ac.firebasestorage.app',
    iosBundleId: 'juny.babyLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsz8cQzLARt2pBPVLm2g3vXed0v7E8aIE',
    appId: '1:695875489529:ios:bd5de05d835e56e1bf1c28',
    messagingSenderId: '695875489529',
    projectId: 'baby-log-894ac',
    storageBucket: 'baby-log-894ac.firebasestorage.app',
    iosBundleId: 'com.example.babyLog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFFsFXj-rCzp7bbtAFXPKWcJ686twGkg0',
    appId: '1:695875489529:web:e28947f3691df3e5bf1c28',
    messagingSenderId: '695875489529',
    projectId: 'baby-log-894ac',
    authDomain: 'baby-log-894ac.firebaseapp.com',
    storageBucket: 'baby-log-894ac.firebasestorage.app',
    measurementId: 'G-18FC38ESJ8',
  );
}
